server:
  port: 8300
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.74.81:8848
  application:
    name: web-all
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

