spring:
  redis:
    host: 192.168.200.128
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  application:
    name: service-item
server:
  port: 8301
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000