fdfs:
  soTimeout: 1500
  connectTimeout: 6000
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 192.168.200.128:22122
project:
  dfsUrl: http://192.168.200.128:8080/
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  application:
    name: product-service
  redis:
    host: 192.168.200.128
    port: 6379

