spring:
  redis:
    host: 47.115.74.81
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.74.81:8848
  application:
    name: service-list
  elasticsearch:
    rest:
      uris: http://47.115.74.81:9200
server:
  port: 8302
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000