spring:
  rabbitmq:
    host: 47.115.74.81
    port: 5672
    username: xuanhe
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #默认情况下消息消费者是自动确认消息的，如果要手动确认消息则需要修改确认模式为manual
        prefetch: 1 # 消费者每次从队列获取的消息数量。此属性当不设置时为：轮询分发，设置为1为：公平分发
    virtual-host: /xuanhe
  redis:
    host: 47.115.74.81
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.74.81:8848
  application:
    name: service-list
  elasticsearch:
    rest:
      uris: http://47.115.74.81:9200
server:
  port: 8302
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000