spring:
  redis:
    host: 192.168.200.128
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  application:
    name: service-list
  elasticsearch:
    rest:
      uris: http://192.168.200.128:9200
server:
  port: 8302
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000